// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qrakdjzdnpvjwqwfocuf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFyYWtkanpkbnB2andxd2ZvY3VmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0OTg5NjMsImV4cCI6MjA3MTA3NDk2M30.KjRRxIAT79ukfyA3SST5wj_eDMH7mIZ9lpfy86PghN4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});